### PR TITLE
signup and login

### PR DESCRIPTION
**Pull request by ap766**
Do let me what has to fixed.

### CODE REVIEW

**Comment by prathamkandari** [comment]
@ap766 Will you please send the screenshots of your work on Swayam-Bazaar workspace

**Comment by ap766** [comment]
@prathamkandari the output?

**Comment by prathamkandari** [comment]
@ap766 yes the output screenshot

**Comment by ap766** [comment]
I dont see a channel for workspace..there's only github updates showing for me

**Comment by prathamkandari** [comment]
@ap766 Ohh okay.. Well you can share me over here

**Comment by ap766** [comment]
Should I remove the jwt authentication for now

**Comment by prathamkandari** [comment]
Let it be like that

**Pull request merged**
