### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by karthiknadar1204**
Simplified process of making a pr

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
Clears #17

**Comment by karthiknadar1204** [comment]
Points for this @prathamkandari ?

**Comment by prathamkandari** [comment]
Readme looks good @karthiknadar1204

**Comment by karthiknadar1204** [comment]
@prathamkandari are there points for this?

**Comment by prathamkandari** [comment]
No points for readme updatio

**Pull request merged**
